// Generated by gencpp from file steering/Action1Goal.msg
// DO NOT EDIT!


#ifndef STEERING_MESSAGE_ACTION1GOAL_H
#define STEERING_MESSAGE_ACTION1GOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace steering
{
template <class ContainerAllocator>
struct Action1Goal_
{
  typedef Action1Goal_<ContainerAllocator> Type;

  Action1Goal_()
    {
    }
  Action1Goal_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::steering::Action1Goal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steering::Action1Goal_<ContainerAllocator> const> ConstPtr;

}; // struct Action1Goal_

typedef ::steering::Action1Goal_<std::allocator<void> > Action1Goal;

typedef boost::shared_ptr< ::steering::Action1Goal > Action1GoalPtr;
typedef boost::shared_ptr< ::steering::Action1Goal const> Action1GoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::steering::Action1Goal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::steering::Action1Goal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace steering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::steering::Action1Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steering::Action1Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::Action1Goal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::Action1Goal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::Action1Goal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::Action1Goal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::steering::Action1Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::steering::Action1Goal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::steering::Action1Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "steering/Action1Goal";
  }

  static const char* value(const ::steering::Action1Goal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::steering::Action1Goal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"\n"
;
  }

  static const char* value(const ::steering::Action1Goal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::steering::Action1Goal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Action1Goal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steering::Action1Goal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::steering::Action1Goal_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // STEERING_MESSAGE_ACTION1GOAL_H
