// Generated by gencpp from file steering/Action1Result.msg
// DO NOT EDIT!


#ifndef STEERING_MESSAGE_ACTION1RESULT_H
#define STEERING_MESSAGE_ACTION1RESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace steering
{
template <class ContainerAllocator>
struct Action1Result_
{
  typedef Action1Result_<ContainerAllocator> Type;

  Action1Result_()
    {
    }
  Action1Result_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::steering::Action1Result_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steering::Action1Result_<ContainerAllocator> const> ConstPtr;

}; // struct Action1Result_

typedef ::steering::Action1Result_<std::allocator<void> > Action1Result;

typedef boost::shared_ptr< ::steering::Action1Result > Action1ResultPtr;
typedef boost::shared_ptr< ::steering::Action1Result const> Action1ResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::steering::Action1Result_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::steering::Action1Result_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace steering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::steering::Action1Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steering::Action1Result_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::Action1Result_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::Action1Result_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::Action1Result_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::Action1Result_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::steering::Action1Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::steering::Action1Result_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::steering::Action1Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "steering/Action1Result";
  }

  static const char* value(const ::steering::Action1Result_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::steering::Action1Result_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
;
  }

  static const char* value(const ::steering::Action1Result_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::steering::Action1Result_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Action1Result_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steering::Action1Result_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::steering::Action1Result_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // STEERING_MESSAGE_ACTION1RESULT_H
