// Generated by gencpp from file steering/Command.msg
// DO NOT EDIT!


#ifndef STEERING_MESSAGE_COMMAND_H
#define STEERING_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace steering
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : command(0)
    , state(0)
    , input_mode(0)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : command(0)
    , state(0)
    , input_mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _command_type;
  _command_type command;

   typedef int32_t _state_type;
  _state_type state;

   typedef int32_t _input_mode_type;
  _input_mode_type input_mode;





  typedef boost::shared_ptr< ::steering::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steering::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::steering::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::steering::Command > CommandPtr;
typedef boost::shared_ptr< ::steering::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::steering::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::steering::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::steering::Command_<ContainerAllocator1> & lhs, const ::steering::Command_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.state == rhs.state &&
    lhs.input_mode == rhs.input_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::steering::Command_<ContainerAllocator1> & lhs, const ::steering::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace steering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::steering::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steering::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::steering::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a39bebcff88cc716167e57a675f085d3";
  }

  static const char* value(const ::steering::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa39bebcff88cc716ULL;
  static const uint64_t static_value2 = 0x167e57a675f085d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::steering::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "steering/Command";
  }

  static const char* value(const ::steering::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::steering::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 command\n"
"int32 state\n"
"int32 input_mode\n"
;
  }

  static const char* value(const ::steering::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::steering::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.state);
      stream.next(m.input_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steering::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::steering::Command_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
    s << indent << "input_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.input_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEERING_MESSAGE_COMMAND_H
