// Generated by gencpp from file steering/input_mode.msg
// DO NOT EDIT!


#ifndef STEERING_MESSAGE_INPUT_MODE_H
#define STEERING_MESSAGE_INPUT_MODE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace steering
{
template <class ContainerAllocator>
struct input_mode_
{
  typedef input_mode_<ContainerAllocator> Type;

  input_mode_()
    : id(0)
    , input_mode(0)  {
    }
  input_mode_(const ContainerAllocator& _alloc)
    : id(0)
    , input_mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _input_mode_type;
  _input_mode_type input_mode;





  typedef boost::shared_ptr< ::steering::input_mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steering::input_mode_<ContainerAllocator> const> ConstPtr;

}; // struct input_mode_

typedef ::steering::input_mode_<std::allocator<void> > input_mode;

typedef boost::shared_ptr< ::steering::input_mode > input_modePtr;
typedef boost::shared_ptr< ::steering::input_mode const> input_modeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::steering::input_mode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::steering::input_mode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::steering::input_mode_<ContainerAllocator1> & lhs, const ::steering::input_mode_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.input_mode == rhs.input_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::steering::input_mode_<ContainerAllocator1> & lhs, const ::steering::input_mode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace steering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::steering::input_mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steering::input_mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::input_mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::input_mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::input_mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::input_mode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::steering::input_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c66a5f62b7a0de9706717ec3def6b7d9";
  }

  static const char* value(const ::steering::input_mode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc66a5f62b7a0de97ULL;
  static const uint64_t static_value2 = 0x06717ec3def6b7d9ULL;
};

template<class ContainerAllocator>
struct DataType< ::steering::input_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "steering/input_mode";
  }

  static const char* value(const ::steering::input_mode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::steering::input_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"int32 input_mode\n"
;
  }

  static const char* value(const ::steering::input_mode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::steering::input_mode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.input_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct input_mode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steering::input_mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::steering::input_mode_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "input_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.input_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEERING_MESSAGE_INPUT_MODE_H
