// Generated by gencpp from file steering/Message1.msg
// DO NOT EDIT!


#ifndef STEERING_MESSAGE_MESSAGE1_H
#define STEERING_MESSAGE_MESSAGE1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace steering
{
template <class ContainerAllocator>
struct Message1_
{
  typedef Message1_<ContainerAllocator> Type;

  Message1_()
    {
    }
  Message1_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::steering::Message1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steering::Message1_<ContainerAllocator> const> ConstPtr;

}; // struct Message1_

typedef ::steering::Message1_<std::allocator<void> > Message1;

typedef boost::shared_ptr< ::steering::Message1 > Message1Ptr;
typedef boost::shared_ptr< ::steering::Message1 const> Message1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::steering::Message1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::steering::Message1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace steering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::steering::Message1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steering::Message1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::Message1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::Message1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::Message1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::Message1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::steering::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::steering::Message1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::steering::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "steering/Message1";
  }

  static const char* value(const ::steering::Message1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::steering::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::steering::Message1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::steering::Message1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Message1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steering::Message1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::steering::Message1_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // STEERING_MESSAGE_MESSAGE1_H
