// Generated by gencpp from file steering/requested_state.msg
// DO NOT EDIT!


#ifndef STEERING_MESSAGE_REQUESTED_STATE_H
#define STEERING_MESSAGE_REQUESTED_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace steering
{
template <class ContainerAllocator>
struct requested_state_
{
  typedef requested_state_<ContainerAllocator> Type;

  requested_state_()
    : id(0)
    , state(0)  {
    }
  requested_state_(const ContainerAllocator& _alloc)
    : id(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::steering::requested_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steering::requested_state_<ContainerAllocator> const> ConstPtr;

}; // struct requested_state_

typedef ::steering::requested_state_<std::allocator<void> > requested_state;

typedef boost::shared_ptr< ::steering::requested_state > requested_statePtr;
typedef boost::shared_ptr< ::steering::requested_state const> requested_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::steering::requested_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::steering::requested_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::steering::requested_state_<ContainerAllocator1> & lhs, const ::steering::requested_state_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::steering::requested_state_<ContainerAllocator1> & lhs, const ::steering::requested_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace steering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::steering::requested_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steering::requested_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::requested_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::requested_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::requested_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::requested_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::steering::requested_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3fdde48f5246eb6df156a2d2049862b";
  }

  static const char* value(const ::steering::requested_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3fdde48f5246eb6ULL;
  static const uint64_t static_value2 = 0xdf156a2d2049862bULL;
};

template<class ContainerAllocator>
struct DataType< ::steering::requested_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "steering/requested_state";
  }

  static const char* value(const ::steering::requested_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::steering::requested_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"int32 state\n"
;
  }

  static const char* value(const ::steering::requested_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::steering::requested_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct requested_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steering::requested_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::steering::requested_state_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEERING_MESSAGE_REQUESTED_STATE_H
