// Generated by gencpp from file steering/Service1.msg
// DO NOT EDIT!


#ifndef STEERING_MESSAGE_SERVICE1_H
#define STEERING_MESSAGE_SERVICE1_H

#include <ros/service_traits.h>


#include <steering/Service1Request.h>
#include <steering/Service1Response.h>


namespace steering
{

struct Service1
{

typedef Service1Request Request;
typedef Service1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Service1
} // namespace steering


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::steering::Service1 > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::steering::Service1&) { return value(); }
};

template<>
struct DataType< ::steering::Service1 > {
  static const char* value()
  {
    return "steering/Service1";
  }

  static const char* value(const ::steering::Service1&) { return value(); }
};


// service_traits::MD5Sum< ::steering::Service1Request> should match
// service_traits::MD5Sum< ::steering::Service1 >
template<>
struct MD5Sum< ::steering::Service1Request>
{
  static const char* value()
  {
    return MD5Sum< ::steering::Service1 >::value();
  }
  static const char* value(const ::steering::Service1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::steering::Service1Request> should match
// service_traits::DataType< ::steering::Service1 >
template<>
struct DataType< ::steering::Service1Request>
{
  static const char* value()
  {
    return DataType< ::steering::Service1 >::value();
  }
  static const char* value(const ::steering::Service1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::steering::Service1Response> should match
// service_traits::MD5Sum< ::steering::Service1 >
template<>
struct MD5Sum< ::steering::Service1Response>
{
  static const char* value()
  {
    return MD5Sum< ::steering::Service1 >::value();
  }
  static const char* value(const ::steering::Service1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::steering::Service1Response> should match
// service_traits::DataType< ::steering::Service1 >
template<>
struct DataType< ::steering::Service1Response>
{
  static const char* value()
  {
    return DataType< ::steering::Service1 >::value();
  }
  static const char* value(const ::steering::Service1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STEERING_MESSAGE_SERVICE1_H
