// Generated by gencpp from file steering/Steering_loopResult.msg
// DO NOT EDIT!


#ifndef STEERING_MESSAGE_STEERING_LOOPRESULT_H
#define STEERING_MESSAGE_STEERING_LOOPRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace steering
{
template <class ContainerAllocator>
struct Steering_loopResult_
{
  typedef Steering_loopResult_<ContainerAllocator> Type;

  Steering_loopResult_()
    : movement_done(false)
    , result_position(0.0)  {
    }
  Steering_loopResult_(const ContainerAllocator& _alloc)
    : movement_done(false)
    , result_position(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _movement_done_type;
  _movement_done_type movement_done;

   typedef float _result_position_type;
  _result_position_type result_position;





  typedef boost::shared_ptr< ::steering::Steering_loopResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::steering::Steering_loopResult_<ContainerAllocator> const> ConstPtr;

}; // struct Steering_loopResult_

typedef ::steering::Steering_loopResult_<std::allocator<void> > Steering_loopResult;

typedef boost::shared_ptr< ::steering::Steering_loopResult > Steering_loopResultPtr;
typedef boost::shared_ptr< ::steering::Steering_loopResult const> Steering_loopResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::steering::Steering_loopResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::steering::Steering_loopResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::steering::Steering_loopResult_<ContainerAllocator1> & lhs, const ::steering::Steering_loopResult_<ContainerAllocator2> & rhs)
{
  return lhs.movement_done == rhs.movement_done &&
    lhs.result_position == rhs.result_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::steering::Steering_loopResult_<ContainerAllocator1> & lhs, const ::steering::Steering_loopResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace steering

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::steering::Steering_loopResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::steering::Steering_loopResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::Steering_loopResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::steering::Steering_loopResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::Steering_loopResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::steering::Steering_loopResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::steering::Steering_loopResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a99868e9ad2b15f76f29eb5217e35ef4";
  }

  static const char* value(const ::steering::Steering_loopResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa99868e9ad2b15f7ULL;
  static const uint64_t static_value2 = 0x6f29eb5217e35ef4ULL;
};

template<class ContainerAllocator>
struct DataType< ::steering::Steering_loopResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "steering/Steering_loopResult";
  }

  static const char* value(const ::steering::Steering_loopResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::steering::Steering_loopResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"bool movement_done\n"
"float32 result_position\n"
;
  }

  static const char* value(const ::steering::Steering_loopResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::steering::Steering_loopResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.movement_done);
      stream.next(m.result_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Steering_loopResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::steering::Steering_loopResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::steering::Steering_loopResult_<ContainerAllocator>& v)
  {
    s << indent << "movement_done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.movement_done);
    s << indent << "result_position: ";
    Printer<float>::stream(s, indent + "  ", v.result_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STEERING_MESSAGE_STEERING_LOOPRESULT_H
