float64 command
int8 Axis_State
int32 Control_Mode
int32 Input_Mode
float32 Input_Position
uint16 Input_Velocity_FF
uint16 Input_Torque_FF
float32 Input_Torque
float32 Velocity_Limit
float32 Current_Limit
float32 Traj_Velocity_Limit
float32 Traj_Accel_Limit
float32 Traj_Decel_Limit
float32 Traj_Inertia
float32 Position
float32 Pos_Gain
float32 Vel_Gain
float32 Vel_Integrator_Gain
---
int32 Axis_Error
int8 Axis_State
int32 Active_Errors
int32 Disarm_Reason
int32 Pos_Estimate
int32 Vel_Estimate
int32 Iq_Setpoint
int32 Iq_Measured
int32 FET_Temperature
int32 Motor_Temperature
int32 Vbus_Voltage
int32 Vbus_Current