// Auto-generated. Do not edit!

// (in-package steering.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class Steering_loopGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.new_position = null;
    }
    else {
      if (initObj.hasOwnProperty('new_position')) {
        this.new_position = initObj.new_position
      }
      else {
        this.new_position = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type Steering_loopGoal
    // Serialize message field [new_position]
    bufferOffset = _serializer.float32(obj.new_position, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type Steering_loopGoal
    let len;
    let data = new Steering_loopGoal(null);
    // Deserialize message field [new_position]
    data.new_position = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'steering/Steering_loopGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '940f1920ef9177c4320784fe9585b6e9';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    float32 new_position
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new Steering_loopGoal(null);
    if (msg.new_position !== undefined) {
      resolved.new_position = msg.new_position;
    }
    else {
      resolved.new_position = 0.0
    }

    return resolved;
    }
};

module.exports = Steering_loopGoal;
