// Auto-generated. Do not edit!

// (in-package steering.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class Steering_loopResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.movement_done = null;
    }
    else {
      if (initObj.hasOwnProperty('movement_done')) {
        this.movement_done = initObj.movement_done
      }
      else {
        this.movement_done = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type Steering_loopResult
    // Serialize message field [movement_done]
    bufferOffset = _serializer.bool(obj.movement_done, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type Steering_loopResult
    let len;
    let data = new Steering_loopResult(null);
    // Deserialize message field [movement_done]
    data.movement_done = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'steering/Steering_loopResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5fa7b13e5c043e733d74b099cb87b938';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    bool movement_done
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new Steering_loopResult(null);
    if (msg.movement_done !== undefined) {
      resolved.movement_done = msg.movement_done;
    }
    else {
      resolved.movement_done = false
    }

    return resolved;
    }
};

module.exports = Steering_loopResult;
