; Auto-generated. Do not edit!


(cl:in-package respond-msg)


;//! \htmlinclude Steering_loopResult.msg.html

(cl:defclass <Steering_loopResult> (roslisp-msg-protocol:ros-message)
  ((movement_done
    :reader movement_done
    :initarg :movement_done
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass Steering_loopResult (<Steering_loopResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Steering_loopResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Steering_loopResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name respond-msg:<Steering_loopResult> is deprecated: use respond-msg:Steering_loopResult instead.")))

(cl:ensure-generic-function 'movement_done-val :lambda-list '(m))
(cl:defmethod movement_done-val ((m <Steering_loopResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader respond-msg:movement_done-val is deprecated.  Use respond-msg:movement_done instead.")
  (movement_done m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Steering_loopResult>) ostream)
  "Serializes a message object of type '<Steering_loopResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'movement_done) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Steering_loopResult>) istream)
  "Deserializes a message object of type '<Steering_loopResult>"
    (cl:setf (cl:slot-value msg 'movement_done) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Steering_loopResult>)))
  "Returns string type for a message object of type '<Steering_loopResult>"
  "respond/Steering_loopResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Steering_loopResult)))
  "Returns string type for a message object of type 'Steering_loopResult"
  "respond/Steering_loopResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Steering_loopResult>)))
  "Returns md5sum for a message object of type '<Steering_loopResult>"
  "5fa7b13e5c043e733d74b099cb87b938")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Steering_loopResult)))
  "Returns md5sum for a message object of type 'Steering_loopResult"
  "5fa7b13e5c043e733d74b099cb87b938")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Steering_loopResult>)))
  "Returns full string definition for message of type '<Steering_loopResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool movement_done~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Steering_loopResult)))
  "Returns full string definition for message of type 'Steering_loopResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool movement_done~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Steering_loopResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Steering_loopResult>))
  "Converts a ROS message object to a list"
  (cl:list 'Steering_loopResult
    (cl:cons ':movement_done (movement_done msg))
))
