// Generated by gencpp from file respond/Desired_angleResponse.msg
// DO NOT EDIT!


#ifndef RESPOND_MESSAGE_DESIRED_ANGLERESPONSE_H
#define RESPOND_MESSAGE_DESIRED_ANGLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace respond
{
template <class ContainerAllocator>
struct Desired_angleResponse_
{
  typedef Desired_angleResponse_<ContainerAllocator> Type;

  Desired_angleResponse_()
    : state(false)  {
    }
  Desired_angleResponse_(const ContainerAllocator& _alloc)
    : state(false)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::respond::Desired_angleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::respond::Desired_angleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Desired_angleResponse_

typedef ::respond::Desired_angleResponse_<std::allocator<void> > Desired_angleResponse;

typedef boost::shared_ptr< ::respond::Desired_angleResponse > Desired_angleResponsePtr;
typedef boost::shared_ptr< ::respond::Desired_angleResponse const> Desired_angleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::respond::Desired_angleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::respond::Desired_angleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::respond::Desired_angleResponse_<ContainerAllocator1> & lhs, const ::respond::Desired_angleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::respond::Desired_angleResponse_<ContainerAllocator1> & lhs, const ::respond::Desired_angleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace respond

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::respond::Desired_angleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::respond::Desired_angleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::respond::Desired_angleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::respond::Desired_angleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::respond::Desired_angleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::respond::Desired_angleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::respond::Desired_angleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "001fde3cab9e313a150416ff09c08ee4";
  }

  static const char* value(const ::respond::Desired_angleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x001fde3cab9e313aULL;
  static const uint64_t static_value2 = 0x150416ff09c08ee4ULL;
};

template<class ContainerAllocator>
struct DataType< ::respond::Desired_angleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "respond/Desired_angleResponse";
  }

  static const char* value(const ::respond::Desired_angleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::respond::Desired_angleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool state\n"
;
  }

  static const char* value(const ::respond::Desired_angleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::respond::Desired_angleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Desired_angleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::respond::Desired_angleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::respond::Desired_angleResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESPOND_MESSAGE_DESIRED_ANGLERESPONSE_H
