// Generated by gencpp from file respond/Odrive_commandRequest.msg
// DO NOT EDIT!


#ifndef RESPOND_MESSAGE_ODRIVE_COMMANDREQUEST_H
#define RESPOND_MESSAGE_ODRIVE_COMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace respond
{
template <class ContainerAllocator>
struct Odrive_commandRequest_
{
  typedef Odrive_commandRequest_<ContainerAllocator> Type;

  Odrive_commandRequest_()
    : command(0)
    , values()  {
    }
  Odrive_commandRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _command_type;
  _command_type command;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::respond::Odrive_commandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::respond::Odrive_commandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Odrive_commandRequest_

typedef ::respond::Odrive_commandRequest_<std::allocator<void> > Odrive_commandRequest;

typedef boost::shared_ptr< ::respond::Odrive_commandRequest > Odrive_commandRequestPtr;
typedef boost::shared_ptr< ::respond::Odrive_commandRequest const> Odrive_commandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::respond::Odrive_commandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::respond::Odrive_commandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::respond::Odrive_commandRequest_<ContainerAllocator1> & lhs, const ::respond::Odrive_commandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::respond::Odrive_commandRequest_<ContainerAllocator1> & lhs, const ::respond::Odrive_commandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace respond

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::respond::Odrive_commandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::respond::Odrive_commandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::respond::Odrive_commandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::respond::Odrive_commandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::respond::Odrive_commandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::respond::Odrive_commandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::respond::Odrive_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6b43d426bfd3f44e42ee21d5f192930";
  }

  static const char* value(const ::respond::Odrive_commandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6b43d426bfd3f44ULL;
  static const uint64_t static_value2 = 0xe42ee21d5f192930ULL;
};

template<class ContainerAllocator>
struct DataType< ::respond::Odrive_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "respond/Odrive_commandRequest";
  }

  static const char* value(const ::respond::Odrive_commandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::respond::Odrive_commandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 command\n"
"float64[] values\n"
;
  }

  static const char* value(const ::respond::Odrive_commandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::respond::Odrive_commandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Odrive_commandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::respond::Odrive_commandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::respond::Odrive_commandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESPOND_MESSAGE_ODRIVE_COMMANDREQUEST_H
