// Generated by gencpp from file respond/Odrive_command.msg
// DO NOT EDIT!


#ifndef RESPOND_MESSAGE_ODRIVE_COMMAND_H
#define RESPOND_MESSAGE_ODRIVE_COMMAND_H

#include <ros/service_traits.h>


#include <respond/Odrive_commandRequest.h>
#include <respond/Odrive_commandResponse.h>


namespace respond
{

struct Odrive_command
{

typedef Odrive_commandRequest Request;
typedef Odrive_commandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Odrive_command
} // namespace respond


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::respond::Odrive_command > {
  static const char* value()
  {
    return "91fd6849a5ae678705e41a8ee4fb22ea";
  }

  static const char* value(const ::respond::Odrive_command&) { return value(); }
};

template<>
struct DataType< ::respond::Odrive_command > {
  static const char* value()
  {
    return "respond/Odrive_command";
  }

  static const char* value(const ::respond::Odrive_command&) { return value(); }
};


// service_traits::MD5Sum< ::respond::Odrive_commandRequest> should match
// service_traits::MD5Sum< ::respond::Odrive_command >
template<>
struct MD5Sum< ::respond::Odrive_commandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::respond::Odrive_command >::value();
  }
  static const char* value(const ::respond::Odrive_commandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::respond::Odrive_commandRequest> should match
// service_traits::DataType< ::respond::Odrive_command >
template<>
struct DataType< ::respond::Odrive_commandRequest>
{
  static const char* value()
  {
    return DataType< ::respond::Odrive_command >::value();
  }
  static const char* value(const ::respond::Odrive_commandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::respond::Odrive_commandResponse> should match
// service_traits::MD5Sum< ::respond::Odrive_command >
template<>
struct MD5Sum< ::respond::Odrive_commandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::respond::Odrive_command >::value();
  }
  static const char* value(const ::respond::Odrive_commandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::respond::Odrive_commandResponse> should match
// service_traits::DataType< ::respond::Odrive_command >
template<>
struct DataType< ::respond::Odrive_commandResponse>
{
  static const char* value()
  {
    return DataType< ::respond::Odrive_command >::value();
  }
  static const char* value(const ::respond::Odrive_commandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RESPOND_MESSAGE_ODRIVE_COMMAND_H
