(cl:in-package steering-srv)
(cl:export '(COMMAND-VAL
          COMMAND
          AXIS_STATE-VAL
          AXIS_STATE
          CONTROL_MODE-VAL
          CONTROL_MODE
          INPUT_MODE-VAL
          INPUT_MODE
          INPUT_POSITION-VAL
          INPUT_POSITION
          INPUT_VELOCITY_FF-VAL
          INPUT_VELOCITY_FF
          INPUT_TORQUE_FF-VAL
          INPUT_TORQUE_FF
          INPUT_TORQUE-VAL
          INPUT_TORQUE
          VELOCITY_LIMIT-VAL
          VELOCITY_LIMIT
          CURRENT_LIMIT-VAL
          CURRENT_LIMIT
          TRAJ_VELOCITY_LIMIT-VAL
          TRAJ_VELOCITY_LIMIT
          TRAJ_ACCEL_LIMIT-VAL
          TRAJ_ACCEL_LIMIT
          TRAJ_DECEL_LIMIT-VAL
          TRAJ_DECEL_LIMIT
          TRAJ_INERTIA-VAL
          TRAJ_INERTIA
          POSITION-VAL
          POSITION
          POS_GAIN-VAL
          POS_GAIN
          VEL_GAIN-VAL
          VEL_GAIN
          VEL_INTEGRATOR_GAIN-VAL
          VEL_INTEGRATOR_GAIN
          AXIS_ERROR-VAL
          AXIS_ERROR
          AXIS_STATE-VAL
          AXIS_STATE
          ACTIVE_ERRORS-VAL
          ACTIVE_ERRORS
          DISARM_REASON-VAL
          DISARM_REASON
          POS_ESTIMATE-VAL
          POS_ESTIMATE
          VEL_ESTIMATE-VAL
          VEL_ESTIMATE
          IQ_SETPOINT-VAL
          IQ_SETPOINT
          IQ_MEASURED-VAL
          IQ_MEASURED
          FET_TEMPERATURE-VAL
          FET_TEMPERATURE
          MOTOR_TEMPERATURE-VAL
          MOTOR_TEMPERATURE
          VBUS_VOLTAGE-VAL
          VBUS_VOLTAGE
          VBUS_CURRENT-VAL
          VBUS_CURRENT
))