; Auto-generated. Do not edit!


(cl:in-package steering-msg)


;//! \htmlinclude Action1Feedback.msg.html

(cl:defclass <Action1Feedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass Action1Feedback (<Action1Feedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Action1Feedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Action1Feedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name steering-msg:<Action1Feedback> is deprecated: use steering-msg:Action1Feedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Action1Feedback>) ostream)
  "Serializes a message object of type '<Action1Feedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Action1Feedback>) istream)
  "Deserializes a message object of type '<Action1Feedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Action1Feedback>)))
  "Returns string type for a message object of type '<Action1Feedback>"
  "steering/Action1Feedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Action1Feedback)))
  "Returns string type for a message object of type 'Action1Feedback"
  "steering/Action1Feedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Action1Feedback>)))
  "Returns md5sum for a message object of type '<Action1Feedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Action1Feedback)))
  "Returns md5sum for a message object of type 'Action1Feedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Action1Feedback>)))
  "Returns full string definition for message of type '<Action1Feedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Action1Feedback)))
  "Returns full string definition for message of type 'Action1Feedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Action1Feedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Action1Feedback>))
  "Converts a ROS message object to a list"
  (cl:list 'Action1Feedback
))
