; Auto-generated. Do not edit!


(cl:in-package steering-msg)


;//! \htmlinclude Action1Goal.msg.html

(cl:defclass <Action1Goal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass Action1Goal (<Action1Goal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Action1Goal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Action1Goal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name steering-msg:<Action1Goal> is deprecated: use steering-msg:Action1Goal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Action1Goal>) ostream)
  "Serializes a message object of type '<Action1Goal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Action1Goal>) istream)
  "Deserializes a message object of type '<Action1Goal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Action1Goal>)))
  "Returns string type for a message object of type '<Action1Goal>"
  "steering/Action1Goal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Action1Goal)))
  "Returns string type for a message object of type 'Action1Goal"
  "steering/Action1Goal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Action1Goal>)))
  "Returns md5sum for a message object of type '<Action1Goal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Action1Goal)))
  "Returns md5sum for a message object of type 'Action1Goal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Action1Goal>)))
  "Returns full string definition for message of type '<Action1Goal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Action1Goal)))
  "Returns full string definition for message of type 'Action1Goal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Action1Goal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Action1Goal>))
  "Converts a ROS message object to a list"
  (cl:list 'Action1Goal
))
