; Auto-generated. Do not edit!


(cl:in-package steering-msg)


;//! \htmlinclude Action1Result.msg.html

(cl:defclass <Action1Result> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass Action1Result (<Action1Result>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Action1Result>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Action1Result)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name steering-msg:<Action1Result> is deprecated: use steering-msg:Action1Result instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Action1Result>) ostream)
  "Serializes a message object of type '<Action1Result>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Action1Result>) istream)
  "Deserializes a message object of type '<Action1Result>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Action1Result>)))
  "Returns string type for a message object of type '<Action1Result>"
  "steering/Action1Result")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Action1Result)))
  "Returns string type for a message object of type 'Action1Result"
  "steering/Action1Result")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Action1Result>)))
  "Returns md5sum for a message object of type '<Action1Result>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Action1Result)))
  "Returns md5sum for a message object of type 'Action1Result"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Action1Result>)))
  "Returns full string definition for message of type '<Action1Result>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Action1Result)))
  "Returns full string definition for message of type 'Action1Result"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Action1Result>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Action1Result>))
  "Converts a ROS message object to a list"
  (cl:list 'Action1Result
))
