; Auto-generated. Do not edit!


(cl:in-package steering-msg)


;//! \htmlinclude Steering_loopResult.msg.html

(cl:defclass <Steering_loopResult> (roslisp-msg-protocol:ros-message)
  ((movement_done
    :reader movement_done
    :initarg :movement_done
    :type cl:boolean
    :initform cl:nil)
   (result_position
    :reader result_position
    :initarg :result_position
    :type cl:float
    :initform 0.0))
)

(cl:defclass Steering_loopResult (<Steering_loopResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Steering_loopResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Steering_loopResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name steering-msg:<Steering_loopResult> is deprecated: use steering-msg:Steering_loopResult instead.")))

(cl:ensure-generic-function 'movement_done-val :lambda-list '(m))
(cl:defmethod movement_done-val ((m <Steering_loopResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader steering-msg:movement_done-val is deprecated.  Use steering-msg:movement_done instead.")
  (movement_done m))

(cl:ensure-generic-function 'result_position-val :lambda-list '(m))
(cl:defmethod result_position-val ((m <Steering_loopResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader steering-msg:result_position-val is deprecated.  Use steering-msg:result_position instead.")
  (result_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Steering_loopResult>) ostream)
  "Serializes a message object of type '<Steering_loopResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'movement_done) 1 0)) ostream)
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'result_position))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Steering_loopResult>) istream)
  "Deserializes a message object of type '<Steering_loopResult>"
    (cl:setf (cl:slot-value msg 'movement_done) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'result_position) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Steering_loopResult>)))
  "Returns string type for a message object of type '<Steering_loopResult>"
  "steering/Steering_loopResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Steering_loopResult)))
  "Returns string type for a message object of type 'Steering_loopResult"
  "steering/Steering_loopResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Steering_loopResult>)))
  "Returns md5sum for a message object of type '<Steering_loopResult>"
  "a99868e9ad2b15f76f29eb5217e35ef4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Steering_loopResult)))
  "Returns md5sum for a message object of type 'Steering_loopResult"
  "a99868e9ad2b15f76f29eb5217e35ef4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Steering_loopResult>)))
  "Returns full string definition for message of type '<Steering_loopResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool movement_done~%float32 result_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Steering_loopResult)))
  "Returns full string definition for message of type 'Steering_loopResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%bool movement_done~%float32 result_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Steering_loopResult>))
  (cl:+ 0
     1
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Steering_loopResult>))
  "Converts a ROS message object to a list"
  (cl:list 'Steering_loopResult
    (cl:cons ':movement_done (movement_done msg))
    (cl:cons ':result_position (result_position msg))
))
