; Auto-generated. Do not edit!


(cl:in-package steering-msg)


;//! \htmlinclude Steering_loopFeedback.msg.html

(cl:defclass <Steering_loopFeedback> (roslisp-msg-protocol:ros-message)
  ((current_position
    :reader current_position
    :initarg :current_position
    :type cl:float
    :initform 0.0))
)

(cl:defclass Steering_loopFeedback (<Steering_loopFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <Steering_loopFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'Steering_loopFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name steering-msg:<Steering_loopFeedback> is deprecated: use steering-msg:Steering_loopFeedback instead.")))

(cl:ensure-generic-function 'current_position-val :lambda-list '(m))
(cl:defmethod current_position-val ((m <Steering_loopFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader steering-msg:current_position-val is deprecated.  Use steering-msg:current_position instead.")
  (current_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <Steering_loopFeedback>) ostream)
  "Serializes a message object of type '<Steering_loopFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'current_position))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <Steering_loopFeedback>) istream)
  "Deserializes a message object of type '<Steering_loopFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'current_position) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<Steering_loopFeedback>)))
  "Returns string type for a message object of type '<Steering_loopFeedback>"
  "steering/Steering_loopFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'Steering_loopFeedback)))
  "Returns string type for a message object of type 'Steering_loopFeedback"
  "steering/Steering_loopFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<Steering_loopFeedback>)))
  "Returns md5sum for a message object of type '<Steering_loopFeedback>"
  "a447468e6d196264c01d04f925289e8a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'Steering_loopFeedback)))
  "Returns md5sum for a message object of type 'Steering_loopFeedback"
  "a447468e6d196264c01d04f925289e8a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<Steering_loopFeedback>)))
  "Returns full string definition for message of type '<Steering_loopFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 current_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'Steering_loopFeedback)))
  "Returns full string definition for message of type 'Steering_loopFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 current_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <Steering_loopFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <Steering_loopFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'Steering_loopFeedback
    (cl:cons ':current_position (current_position msg))
))
